---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    SERVICES__USERAPIRESOURCEID: http://vh-bookings-api.demo.platform.hmcts.net

