//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("1.6.1.0")]
[assembly: AssemblyVersion("1.6.1.0")]
[assembly: AssemblyInformationalVersion("1.6.1-VIH-5629-Add-version-property-to-healthcheck-endpoint.1+25.Branch.feature-VIH-5629-Add-version-property-to-healthcheck-endpoint.Sha.380d3ccca98bd8e40644997952fced17eea9c64a")]