using FluentAssertions;
using NUnit.Framework;
using UserApi.Helper;

namespace UserApi.UnitTests.Helpers.StringSanitiserTests;

public class RemoveAccentsTests
{
    [TestCase("José", "Jose")]
    [TestCase("Köln", "Koln")]
    [TestCase("Haçienda", "Hacienda")]
    [TestCase("Çréâtïvéàççénts", "Creativeaccents")]
    [TestCase("Áá","Aa")]
    [TestCase("Àà","Aa")]
    [TestCase("Ââ","Aa")]
    [TestCase("Ää","Aa")]
    [TestCase("Ãã","Aa")]
    [TestCase("Åå","Aa")]
    [TestCase("Āā","Aa")]
    [TestCase("Ăă","Aa")]
    [TestCase("Ąą","Aa")]
    [TestCase("Ćć","Cc")]
    [TestCase("Ĉĉ","Cc")]
    [TestCase("Ċċ","Cc")]
    [TestCase("Čč","Cc")]
    [TestCase("Ðð","Dd")]
    [TestCase("Éé","Ee")]
    [TestCase("Èè","Ee")]
    [TestCase("Êê","Ee")]
    [TestCase("Ëë","Ee")]
    [TestCase("Ēē","Ee")]
    [TestCase("Ĕĕ","Ee")]
    [TestCase("Ėė","Ee")]
    [TestCase("Ęę","Ee")]
    [TestCase("Ěě","Ee")]
    [TestCase("Ĝĝ","Gg")]
    [TestCase("Ğğ","Gg")]
    [TestCase("Ġġ","Gg")]
    [TestCase("Ģģ","Gg")]
    [TestCase("Ĥĥ","Hh")]
    [TestCase("Ħħ","Hh")]
    [TestCase("Íí","Ii")]
    [TestCase("Ìì","Ii")]
    [TestCase("Îî","Ii")]
    [TestCase("Ïï","Ii")]
    [TestCase("Ĩĩ","Ii")]
    [TestCase("Īī","Ii")]
    [TestCase("Ĭĭ","Ii")]
    [TestCase("Įį","Ii")]
    [TestCase("İı","Ii")]
    [TestCase("Ĵĵ","Jj")]
    [TestCase("Ķķ","Kk")]
    [TestCase("Ĺĺ","Ll")]
    [TestCase("Ļļ","Ll")]
    [TestCase("Ľľ","Ll")]
    [TestCase("Łł","Ll")]
    [TestCase("Ńń","Nn")]
    [TestCase("Ņņ","Nn")]
    [TestCase("Ňň","Nn")]
    [TestCase("Ññ","Nn")]
    [TestCase("Óó","Oo")]
    [TestCase("Òò","Oo")]
    [TestCase("Ôô","Oo")]
    [TestCase("Öö","Oo")]
    [TestCase("Õõ","Oo")]
    [TestCase("Øø","Oo")]
    [TestCase("Ōō","Oo")]
    [TestCase("Ŏŏ","Oo")]
    [TestCase("Őő","Oo")]
    [TestCase("Ŕŕ","Rr")]
    [TestCase("Ŗŗ","Rr")]
    [TestCase("Řř","Rr")]
    [TestCase("Śś","Ss")]
    [TestCase("Ŝŝ","Ss")]
    [TestCase("Şş","Ss")]
    [TestCase("Šš","Ss")]
    [TestCase("Ţţ","Tt")]
    [TestCase("Ťť","Tt")]
    [TestCase("Ŧŧ","Tt")]
    [TestCase("Úú","Uu")]
    [TestCase("Ùù","Uu")]
    [TestCase("Ûû","Uu")]
    [TestCase("Üü","Uu")]
    [TestCase("Ũũ","Uu")]
    [TestCase("Ūū","Uu")]
    [TestCase("Ŭŭ","Uu")]
    [TestCase("Ůů","Uu")]
    [TestCase("Űű","Uu")]
    [TestCase("Ųų","Uu")]
    [TestCase("Ŵŵ","Ww")]
    [TestCase("Ẁẁ","Ww")]
    [TestCase("Ẃẃ","Ww")]
    [TestCase("Ẅẅ","Ww")]
    [TestCase("Ýý","Yy")]
    [TestCase("Ỳỳ","Yy")]
    [TestCase("Ŷŷ","Yy")]
    [TestCase("Ÿÿ","Yy")]
    [TestCase("Źź","Zz")]
    [TestCase("Żż","Zz")]
    [TestCase("Žž","Zz")]
    [TestCase("ÐĦħIŁØŦðıłøŧ", "DHhILOTdilot")]
    public void Should_remove_accent(string input, string expected)
    {
        var result = input.RemoveAccents();
        result.Should().Be(expected);
    }
}