version: '3.4'

services:
  userapi:
    container_name: userapi_ac
    build:
      context: UserApi/bin/${CONFIGURATION}/netcoreapp3.1/publish
      dockerfile: ../../../../Dockerfile.publish
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  zapapi:
    image: sspublicsbox.azurecr.io/secops/zaproxy
    container_name: zapapi
    volumes:
      - ./UserApi.AcceptanceTests/zapapi-config.xml:/home/zap/.ZAP/config.xml
    ports:
      - "8080:8080"
